version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: API/VNQuiz.Alice/Dockerfile
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      - ApplicationInsights__InstrumentationKey=${APPLICATIONINSIGHTS__INSTRUMENTATIONKEY}
